# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmberPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Victim', models.CharField(max_length=200)),
                ('Suspect', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
            ],
        ),
    ]
